services:
  - type: web
    name: bengal-bay-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GOOGLE_SHEETS_PRIVATE_KEY
        sync: false
      - key: GOOGLE_SHEETS_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false